import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  appSidebar: [{ type: "autogenerated", dirName: "app" }],
  adminSidebar: [{ type: "autogenerated", dirName: "admin" }],
  codeSidebar: [{ type: "autogenerated", dirName: "code" }],
};

export default sidebars;
